# Generated by Django 2.2.1 on 2019-06-18 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('name',
                 models.CharField(
                     max_length=100,
                     unique=True,
                     verbose_name='Sacco name')),
                ('sacco_id',
                 models.CharField(
                     max_length=100,
                     primary_key=True,
                     serialize=False,
                     verbose_name='Sacco ID')),
                ('manager',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='manager',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Manager')),
            ],
        ),
    ]
