# Generated by Django 2.2.1 on 2019-06-23 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacco',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='accounts.Manager', verbose_name='Manager'),
        ),
    ]
