# Generated by Django 2.2.1 on 2019-06-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_remove_vehicle_vehicle_sacco'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('sacco', '0003_auto_20190623_1408'),
        ('accounts', '0003_driver_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
