# Generated by Django 2.2.1 on 2019-06-18 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('capacity',
                 models.PositiveIntegerField()),
                ('number_plate',
                 models.CharField(
                     max_length=15,
                     primary_key=True,
                     serialize=False,
                     verbose_name='Number plate')),
                ('vehicle_type',
                 models.CharField(
                     choices=[
                         ('A',
                          'Luxury'),
                         ('B',
                          'Standard')],
                     max_length=2)),
                ('driver',
                 models.OneToOneField(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Driver')),
                ('vehicle_sacco',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='sacco.Sacco')),
            ],
        ),
    ]
