# Generated by Django 2.2.1 on 2019-06-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_sacco',
        ),
    ]
