# Generated by Django 2.2.1 on 2019-06-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name',
                 models.CharField(
                     max_length=100,
                     verbose_name='Location')),
                ('location_id',
                 models.CharField(
                     max_length=100,
                     primary_key=True,
                     serialize=False,
                     verbose_name='Location ID')),
            ],
        ),
    ]
